language: php
sudo: false

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly
  
env:
  - COMPOSER_FLAGS=""
  - COMPOSER_FLAGS="--prefer-lowest"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: 
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls
