language: php
sudo: false

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly
  
env:
  - COMPOSER_FLAGS=""
  - COMPOSER_FLAGS="--prefer-lowest"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer update --prefer-dist --no-interaction $COMPOSER_FLAGS
  # Install coveralls.phar
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar -O coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version

script: 
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php coveralls.phar -v
